
(()=>{
'use strict';
const C=window.LITHA_CONFIG||{};
const qs=(s,r=document)=>r.querySelector(s), qsa=(s,r=document)=>[...r.querySelectorAll(s)];
const money=n=>new Intl.NumberFormat('en-ZA',{style:'currency',currency:'ZAR',maximumFractionDigits:0}).format(n||0);
let products=[]; try{products=JSON.parse(qs('#productData')?.textContent||'[]')}catch(e){}
let cart=JSON.parse(localStorage.getItem('lithaCart')||'[]');
let wishlist=JSON.parse(localStorage.getItem('lithaWishlist')||'[]');
const save=()=>{localStorage.setItem('lithaCart',JSON.stringify(cart));localStorage.setItem('lithaWishlist',JSON.stringify(wishlist))};
const product=id=>products.find(p=>p.id===id);
const total=()=>cart.reduce((s,i)=>{const p=product(i.id);return s+(p?p.price*i.qty:0)},0);
function toast(msg){let t=qs('#toast');if(!t){t=document.createElement('div');t.id='toast';t.className='toast';document.body.append(t)}t.textContent=msg;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),2200)}
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function card(p){return `<article class="product-card" data-id="${p.id}" data-category="${p.category}"><div class="product-visual ${p.tone}"><span class="product-badge">${p.badge||p.collection}</span><button class="wish ${wishlist.includes(p.id)?'saved':''}" data-wish="${p.id}" aria-label="Save ${esc(p.name)}">${wishlist.includes(p.id)?'♥':'♡'}</button><div class="product-symbol">${p.symbol}</div><button class="quick" data-view="${p.id}">Quick view</button></div><div class="product-info"><h3>${esc(p.name)}</h3><div class="meta"><span>${esc(p.collection)}</span><span class="price">${money(p.price)}</span></div></div></article>`}
function renderProducts(filter='all', query=''){const grid=qs('#productGrid');if(!grid)return;const q=query.trim().toLowerCase();const list=products.filter(p=>(filter==='all'||p.category===filter)&&(q===''||`${p.name} ${p.collection} ${p.category} ${p.desc}`.toLowerCase().includes(q)));grid.innerHTML=list.length?list.map(card).join(''):'<p>No products found.</p>';}
function updateCounts(){qsa('[data-cart-count]').forEach(x=>x.textContent=cart.reduce((s,i)=>s+i.qty,0));qsa('[data-wish-count]').forEach(x=>x.textContent=wishlist.length)}
function add(id,size,qty=1){const p=product(id);if(!p)return;size=size||p.sizes?.[0]||'One Size';const item=cart.find(x=>x.id===id&&x.size===size);if(item)item.qty+=qty;else cart.push({id,size,qty});save();renderCart();toast(`${p.name} added to bag`)}
function renderCart(){const box=qs('#cartItems');updateCounts();if(!box)return;if(!cart.length){box.innerHTML='<div style="padding:40px 5px"><p>Your bag is empty.</p><a href="shop.html" class="btn btn-dark">Shop collection</a></div>'}else box.innerHTML=cart.map((i,idx)=>{const p=product(i.id);if(!p)return'';return `<div class="cart-item"><div class="cart-thumb">${p.symbol}</div><div><strong>${esc(p.name)}</strong><small>${esc(i.size)} · ${money(p.price)}</small><div class="qty"><button data-qty="${idx}" data-delta="-1" aria-label="Decrease quantity">−</button><span>${i.qty}</span><button data-qty="${idx}" data-delta="1" aria-label="Increase quantity">+</button></div><button class="remove" data-remove="${idx}">Remove</button></div><strong>${money(p.price*i.qty)}</strong></div>`}).join('');const t=total(),threshold=C.freeShippingThreshold||1500,remain=Math.max(0,threshold-t);qs('#cartSubtotal')&&(qs('#cartSubtotal').textContent=money(t));qs('#shipMsg')&&(qs('#shipMsg').textContent=remain?`${money(remain)} away from free SA delivery`:'You unlocked free SA delivery');qs('#shipBar')&&(qs('#shipBar').style.width=`${Math.min(100,t/threshold*100)}%`)}
function openCart(){qs('#cartDrawer')?.classList.add('open');qs('#scrim')?.classList.add('open');document.body.classList.add('lock')}
function closeLayers(){qsa('.drawer,.search-overlay,.modal,.mobile-menu').forEach(x=>x.classList.remove('open'));qs('#scrim')?.classList.remove('open');document.body.classList.remove('lock')}
function openProduct(id){const p=product(id),m=qs('#productModal');if(!p||!m)return;m.dataset.id=id;qs('#modalVisual').className=`modal-visual ${p.tone}`;qs('#modalVisual').textContent=p.symbol;qs('#modalBadge').textContent=p.badge;qs('#modalName').textContent=p.name;qs('#modalPrice').textContent=money(p.price);qs('#modalDesc').textContent=p.desc;qs('#modalCollection').textContent=p.collection;qs('#modalSizes').innerHTML=p.sizes.map((s,i)=>`<button class="size-btn ${i===0?'active':''}" data-size="${esc(s)}">${esc(s)}</button>`).join('');m.classList.add('open');qs('#scrim')?.classList.add('open');document.body.classList.add('lock')}
function search(q){const box=qs('#searchResults');if(!box)return;const term=q.toLowerCase().trim();const list=term?products.filter(p=>`${p.name} ${p.category} ${p.collection}`.toLowerCase().includes(term)).slice(0,9):products.slice(0,6);box.innerHTML=list.map(p=>`<button class="search-result" data-view="${p.id}" style="border:0;text-align:left"><strong>${esc(p.name)}</strong><small style="display:block;color:#777">${esc(p.collection)} · ${money(p.price)}</small></button>`).join('')}
function initQueryFilter(){const grid=qs('#productGrid');if(!grid||grid.dataset.noAuto==='true')return;const params=new URLSearchParams(location.search);const f=params.get('category')||grid.dataset.defaultFilter||'all',q=params.get('q')||'';qsa('.filter').forEach(b=>b.classList.toggle('active',b.dataset.filter===f));renderProducts(f,q);const limit=Number(grid.dataset.limit||0);if(limit){[...grid.children].slice(limit).forEach(x=>x.remove())}if(q&&qs('#shopSearch'))qs('#shopSearch').value=q}
function socials(){qsa('[data-social="instagram"]').forEach(a=>{if(C.instagram){a.href=C.instagram;a.target='_blank';a.rel='noopener'}else{a.addEventListener('click',e=>{e.preventDefault();toast('Instagram link will be activated at launch.')})}});qsa('[data-social="tiktok"]').forEach(a=>{if(C.tiktok){a.href=C.tiktok;a.target='_blank';a.rel='noopener'}else{a.addEventListener('click',e=>{e.preventDefault();toast('TikTok link will be activated at launch.')})}})}
document.addEventListener('click',e=>{const t=e.target.closest('[data-view],[data-add],[data-wish],[data-filter],[data-qty],[data-remove],[data-size]');if(t?.dataset.view){openProduct(t.dataset.view)}if(t?.dataset.add){const p=product(t.dataset.add);add(t.dataset.add,p?.sizes?.[0]);openCart()}if(t?.dataset.wish){const id=t.dataset.wish;wishlist=wishlist.includes(id)?wishlist.filter(x=>x!==id):[...wishlist,id];save();renderProducts(qs('.filter.active')?.dataset.filter||'all',qs('#shopSearch')?.value||'');updateCounts();toast(wishlist.includes(id)?'Saved to wishlist':'Removed from wishlist')}if(t?.dataset.filter){qsa('.filter').forEach(x=>x.classList.remove('active'));t.classList.add('active');renderProducts(t.dataset.filter,qs('#shopSearch')?.value||'')}if(t?.dataset.qty!==undefined){const i=Number(t.dataset.qty);cart[i].qty+=Number(t.dataset.delta);if(cart[i].qty<=0)cart.splice(i,1);save();renderCart()}if(t?.dataset.remove!==undefined){cart.splice(Number(t.dataset.remove),1);save();renderCart()}if(t?.dataset.size){qsa('.size-btn',t.parentElement).forEach(x=>x.classList.remove('active'));t.classList.add('active')}});
qs('#modalAdd')?.addEventListener('click',()=>{const m=qs('#productModal'),size=qs('.size-btn.active',m)?.dataset.size;add(m.dataset.id,size);closeLayers();openCart()});
qs('#cartBtn')?.addEventListener('click',openCart);qs('#scrim')?.addEventListener('click',closeLayers);qsa('[data-close]').forEach(x=>x.addEventListener('click',closeLayers));
qs('#menuBtn')?.addEventListener('click',()=>{qs('#mobileMenu')?.classList.add('open');document.body.classList.add('lock')});qsa('#mobileMenu a').forEach(x=>x.addEventListener('click',closeLayers));
qs('#searchBtn')?.addEventListener('click',()=>{qs('#searchOverlay')?.classList.add('open');document.body.classList.add('lock');search('');setTimeout(()=>qs('#searchInput')?.focus(),60)});qs('#searchInput')?.addEventListener('input',e=>search(e.target.value));qs('#shopSearch')?.addEventListener('input',e=>renderProducts(qs('.filter.active')?.dataset.filter||'all',e.target.value));
qs('#newsletterForm')?.addEventListener('submit',e=>{e.preventDefault();const email=qs('#emailInput')?.value.trim();localStorage.setItem('lithaNewsletterEmail',email);qs('#newsletterMsg').textContent='You’re on the list. Welcome to the ascent.';e.currentTarget.reset();toast('Welcome to the ascent.')});
qsa('.faq-q').forEach(q=>q.addEventListener('click',()=>q.parentElement.classList.toggle('open')));
qs('#backTop')?.addEventListener('click',()=>scrollTo({top:0,behavior:'smooth'}));addEventListener('scroll',()=>qs('#backTop')?.classList.toggle('show',scrollY>800));addEventListener('keydown',e=>{if(e.key==='Escape')closeLayers()});
if('serviceWorker' in navigator && location.protocol.startsWith('http')) navigator.serviceWorker.register('./sw.js').catch(()=>{});
initQueryFilter();renderCart();updateCounts();socials();
})();
